"""Next30Days model features."""
import tensorflow as tf
import tensorflow_model_analysis as tfma
import tensorflow_transform as tft
from tensorflow_transform.tf_metadata import schema_utils

QUERY_TEMPLATE = """

SELECT
    IFNULL(total_sale_units, 0) AS total_sale_units,
    IFNULL(average_sales_price, 0) AS average_sales_price,
    IFNULL(total_orders, 0) AS total_orders,
    IFNULL(total_gross_sales, 0) AS total_gross_sales,
    IFNULL(average_order_value, 0) AS average_order_value,
    IFNULL(average_order_value_15_mo, 0) AS average_order_value_15_mo,
    IFNULL(last_purchase_platform, 'UKN') AS last_purchase_platform,
    IFNULL(days_from_join_to_purchase, 0) AS days_from_join_to_purchase,
    IFNULL(days_since_last_purchase, 0) AS days_since_last_purchase,
    IFNULL(total_gross_sales_last_3_days, 0) AS total_gross_sales_last_3_days,
    IFNULL(total_gross_sales_last_7_days, 0) AS total_gross_sales_last_7_days,
    IFNULL(total_gross_sales_last_15_days, 0) AS total_gross_sales_last_15_days,
    IFNULL(total_gross_sales_last_30_days, 0) AS total_gross_sales_last_30_days,
    IFNULL(average_order_value_last_3_days, 0) AS average_order_value_last_3_days,
    IFNULL(average_order_value_last_7_days, 0) AS average_order_value_last_7_days,
    IFNULL(average_order_value_last_15_days, 0) AS average_order_value_last_15_days,
    IFNULL(average_order_value_last_30_days, 0) AS average_order_value_last_30_days,
    IFNULL(total_sold_units, 0) AS total_sold_units,
    IFNULL(average_sold_price, 0) AS average_sold_price,
    IFNULL(total_sold_last_3_days, 0) AS total_sold_last_3_days,
    IFNULL(total_sold_last_7_days, 0) AS total_sold_last_7_days,
    IFNULL(total_sold_last_15_days, 0) AS total_sold_last_15_days,
    IFNULL(total_sold_last_30_days, 0) AS total_sold_last_30_days,
    IFNULL(num_page_views_last_3_days, 0) AS num_page_views_last_3_days,
    IFNULL(num_page_views_last_7_days, 0) AS num_page_views_last_7_days,
    IFNULL(num_page_views_last_15_days, 0) AS num_page_views_last_15_days,
    IFNULL(num_page_views_last_30_days, 0) AS num_page_views_last_30_days,
    IFNULL(num_obsessions_last_3_days, 0) AS num_obsessions_last_3_days,
    IFNULL(num_obsessions_last_7_days, 0) AS num_obsessions_last_7_days,
    IFNULL(num_obsessions_last_15_days, 0) AS num_obsessions_last_15_days,
    IFNULL(num_obsessions_last_30_days, 0) AS num_obsessions_last_30_days,
    IFNULL(designers_dir_views_last_3_days, 0) AS designers_dir_views_last_3_days,
    IFNULL(designers_dir_views_last_7_days, 0) AS designers_dir_views_last_7_days,
    IFNULL(designers_dir_views_last_15_days, 0) AS designers_dir_views_last_15_days,
    IFNULL(designers_dir_views_last_30_days, 0) AS designers_dir_views_last_30_days,
    IFNULL(cf_landing_views_last_3_days, 0) AS cf_landing_views_last_3_days,
    IFNULL(cf_landing_views_last_7_days, 0) AS cf_landing_views_last_7_days,
    IFNULL(cf_landing_views_last_15_days, 0) AS cf_landing_views_last_15_days,
    IFNULL(cf_landing_views_last_30_days, 0) AS cf_landing_views_last_30_days,
    IFNULL(cf_lead_form_views_last_3_days, 0) AS cf_lead_form_views_last_3_days,
    IFNULL(cf_lead_form_views_last_7_days, 0) AS cf_lead_form_views_last_7_days,
    IFNULL(cf_lead_form_views_last_15_days, 0) AS cf_lead_form_views_last_15_days,
    IFNULL(cf_lead_form_views_last_30_days, 0) AS cf_lead_form_views_last_30_days,
    IFNULL(cf_method_views_last_3_days, 0) AS cf_method_views_last_3_days,
    IFNULL(cf_method_views_last_7_days, 0) AS cf_method_views_last_7_days,
    IFNULL(cf_method_views_last_15_days, 0) AS cf_method_views_last_15_days,
    IFNULL(cf_method_views_last_30_days, 0) AS cf_method_views_last_30_days,
    IFNULL(cf_conf_views_last_3_days, 0) AS cf_conf_views_last_3_days,
    IFNULL(cf_conf_views_last_7_days, 0) AS cf_conf_views_last_7_days,
    IFNULL(cf_conf_views_last_15_days, 0) AS cf_conf_views_last_15_days,
    IFNULL(cf_conf_views_last_30_days, 0) AS cf_conf_views_last_30_days,
    IFNULL(cf_lead_form_submissions_last_3_days, 0) AS cf_lead_form_submissions_last_3_days,
    IFNULL(cf_lead_form_submissions_last_7_days, 0) AS cf_lead_form_submissions_last_7_days,
    IFNULL(cf_lead_form_submissions_last_15_days, 0) AS cf_lead_form_submissions_last_15_days,
    IFNULL(cf_lead_form_submissions_last_30_days, 0) AS cf_lead_form_submissions_last_30_days,
    IFNULL(cf_services_options_views_last_3_days, 0) AS cf_services_options_views_last_3_days,
    IFNULL(cf_services_options_views_last_7_days, 0) AS cf_services_options_views_last_7_days,
    IFNULL(cf_services_options_views_last_15_days, 0) AS cf_services_options_views_last_15_days,
    IFNULL(cf_services_options_views_last_30_days, 0) AS cf_services_options_views_last_30_days,
    IFNULL(item_views_last_3_days, 0) AS item_views_last_3_days,
    IFNULL(item_views_last_7_days, 0) AS item_views_last_7_days,
    IFNULL(item_views_last_15_days, 0) AS item_views_last_15_days,
    IFNULL(item_views_last_30_days, 0) AS item_views_last_30_days,
    IFNULL(emails_opened_last_3_days, 0) AS emails_opened_last_3_days,
    IFNULL(emails_opened_last_7_days, 0) AS emails_opened_last_7_days,
    IFNULL(emails_opened_last_15_days, 0) AS emails_opened_last_15_days,
    IFNULL(emails_opened_last_30_days, 0) AS emails_opened_last_30_days,
    IFNULL(emails_clicked_last_3_days, 0) AS emails_clicked_last_3_days,
    IFNULL(emails_clicked_last_7_days, 0) AS emails_clicked_last_7_days,
    IFNULL(emails_clicked_last_15_days, 0) AS emails_clicked_last_15_days,
    IFNULL(emails_clicked_last_30_days, 0) AS emails_clicked_last_30_days,
    IFNULL(times_consigned, 0) AS times_consigned,
    IFNULL(lifetime_items_consigned, 0) AS lifetime_items_consigned,
    IFNULL(average_unit_price, 0) AS average_unit_price,
    IFNULL(lifetime_retail_consigned, 0) AS lifetime_retail_consigned,
    IFNULL(receive_newsletter, FALSE) AS receive_newsletter,
    IFNULL(count_surveys, 0) AS count_surveys,
    IFNULL(count_promoters, 0) AS count_promoters,
    IFNULL(count_detractors, 0) AS count_detractors,
    IFNULL(count_purchase_surveys, 0) AS count_purchase_surveys,
    IFNULL(count_purchase_promoters, 0) AS count_purchase_promoters,
    IFNULL(count_purchase_detractors, 0) AS count_purchase_detractors,
    IFNULL(count_consign_surveys, 0) AS count_consign_surveys,
    IFNULL(count_consign_promoters, 0) AS count_consign_promoters,
    IFNULL(count_consign_detractors, 0) AS count_consign_detractors,
    IFNULL(count_appt_surveys, 0) AS count_appt_surveys,
    IFNULL(count_appt_promoters, 0) AS count_appt_promoters,
    IFNULL(count_appt_detractors, 0) AS count_appt_detractors,
    IFNULL(lifetime_nps, 0) AS lifetime_nps,
    IFNULL(lifetime_nps_purchase, 0) AS lifetime_nps_purchase,
    IFNULL(lifetime_nps_consign, 0) AS lifetime_nps_consign,
    IFNULL(lifetime_nps_appt, 0) AS lifetime_nps_appt,
    IFNULL(session_types, 'UKN') AS session_types,
    IFNULL(sources, 'UKN') AS sources,
    IFNULL(gender, 'UKN') AS gender,
    IFNULL(age_range, 'UKN') AS age_range,
    IFNULL(income_range_1, 'UKN') AS income_range_1,
    IFNULL(city, 'UKN') AS city,
    IFNULL(state, 'UKN') AS state,
    IFNULL(first_look_subscription_type, 'UKN') AS first_look_subscription_type,
    IFNULL(closest_location, 'UKN') AS closest_location,
    IFNULL(has_inquiry_next_30_days, FALSE) AS has_inquiry_next_30_days,
FROM trr-assignments-staging.trrsample.l2i_{}_dev
WHERE RAND() < 0.05
"""

NUMERIC_FEATURE_KEYS = [
    'total_sale_units',
    'total_orders',
    'days_from_join_to_purchase',
    'days_since_last_purchase',
    'total_sold_units',
    'num_page_views_last_3_days',
    'num_page_views_last_7_days',
    'num_page_views_last_15_days',
    'num_page_views_last_30_days',
    'num_obsessions_last_3_days',
    'num_obsessions_last_7_days',
    'num_obsessions_last_15_days',
    'num_obsessions_last_30_days',
    'designers_dir_views_last_3_days',
    'designers_dir_views_last_7_days',
    'designers_dir_views_last_15_days',
    'designers_dir_views_last_30_days',
    'cf_landing_views_last_3_days',
    'cf_landing_views_last_7_days',
    'cf_landing_views_last_15_days',
    'cf_landing_views_last_30_days',
    'cf_lead_form_views_last_3_days',
    'cf_lead_form_views_last_7_days',
    'cf_lead_form_views_last_15_days',
    'cf_lead_form_views_last_30_days',
    'cf_method_views_last_3_days',
    'cf_method_views_last_7_days',
    'cf_method_views_last_15_days',
    'cf_method_views_last_30_days',
    'cf_conf_views_last_3_days',
    'cf_conf_views_last_7_days',
    'cf_conf_views_last_15_days',
    'cf_conf_views_last_30_days',
    'cf_lead_form_submissions_last_3_days',
    'cf_lead_form_submissions_last_7_days',
    'cf_lead_form_submissions_last_15_days',
    'cf_lead_form_submissions_last_30_days',
    'cf_services_options_views_last_3_days',
    'cf_services_options_views_last_7_days',
    'cf_services_options_views_last_15_days',
    'cf_services_options_views_last_30_days',
    'item_views_last_3_days',
    'item_views_last_7_days',
    'item_views_last_15_days',
    'item_views_last_30_days',
    'emails_opened_last_3_days',
    'emails_opened_last_7_days',
    'emails_opened_last_15_days',
    'emails_opened_last_30_days',
    'emails_clicked_last_3_days',
    'emails_clicked_last_7_days',
    'emails_clicked_last_15_days',
    'emails_clicked_last_30_days',
    'times_consigned',
    'lifetime_items_consigned',
    'count_surveys',
    'count_promoters',
    'count_detractors',
    'count_purchase_surveys',
    'count_purchase_promoters',
    'count_purchase_detractors',
    'count_consign_surveys',
    'count_consign_promoters',
    'count_consign_detractors',
    'count_appt_surveys',
    'count_appt_promoters',
    'count_appt_detractors',
    'average_sales_price',
    'total_gross_sales',
    'average_order_value',
    'average_order_value_15_mo',
    'total_gross_sales_last_3_days',
    'total_gross_sales_last_7_days',
    'total_gross_sales_last_15_days',
    'total_gross_sales_last_30_days',
    'average_order_value_last_3_days',
    'average_order_value_last_7_days',
    'average_order_value_last_15_days',
    'average_order_value_last_30_days',
    'average_sold_price',
    'total_sold_last_3_days',
    'total_sold_last_7_days',
    'total_sold_last_15_days',
    'total_sold_last_30_days',
    'average_unit_price',
    'lifetime_retail_consigned',
    'lifetime_nps',
    'lifetime_nps_purchase',
    'lifetime_nps_consign',
    'lifetime_nps_appt'
]

CATEGORICAL_FEATURE_KEYS = [
  'last_purchase_platform',
  'session_types',
  'sources',
  'gender',
  'age_range',
  'income_range_1',
  'city',
  'state',
  'first_look_subscription_type',
  'closest_location',
  'receive_newsletter'
]
LABEL_KEY = 'has_inquiry_next_30_days'
NUM_CLASSES = 2

def transformed_name(key):
  return key + '_xf'
